"""added sets

Revision ID: 25b9b47d9b7b
Revises: eb95eeeb7681
Create Date: 2022-02-13 14:44:22.486320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b9b47d9b7b'
down_revision = 'eb95eeeb7681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('set_num', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'set_num')
    # ### end Alembic commands ###
